language: node_js

node_js:
- '11'

install:
- npm install -g vsce
- npm install

script:
- vsce package

deploy:
  # deploy to vscode extension market
  - provider: script  
    script: vsce publish patch -p $VSCE_TOKEN --packagePath *.vsix # $VSCE_TOKEN set in travis-ci.org dashboard
    skip_cleanup: true
    on:
      branch: master
